# Generated by Django 4.2.17 on 2024-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.TextField(default="{}"),
        ),
    ]
